source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby '>= 2.7.0'

gem 'cocoapods', '~> 1.12'
gem 'cocoapods-check', '>= 1.1.0'

source "https://rubygems.org"
