name: Build Android App

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-android.yml'
      - 'android/**'
      - 'examples/bare/android/**'
      - 'yarn.lock'
      - 'src/Spec/**'
  pull_request:
    paths:
      - '.github/workflows/build-android.yml'
      - 'android/**'
      - 'examples/bare/android/**'
      - 'yarn.lock'
      - 'src/Spec/**'

jobs:
  build_example:
    name: Build Android Example App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install node_modules
        run: yarn install --immutable

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Gradle Build for examples/bare/android/
        run: cd examples/bare/android && ./gradlew assembleDebug --build-cache && cd ../../..
