name: Validate Android

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/validate-android.yml'
      - 'android/**'
      - '.editorconfig'
  pull_request:
    paths:
      - '.github/workflows/validate-android.yml'
      - 'android/**'
      - '.editorconfig'

jobs:
  lint:
    name: Gradle Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/bare/android
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Install node_modules
        run: yarn install --immutable
        working-directory: .

      - name: Restore Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run Gradle Lint
        run: ./gradlew lint --build-cache

      - name: Parse Gradle Lint Report
        uses: yutailang0119/action-android-lint@v3.1.0
        with:
          report-path: examples/bare/android/build/reports/lint-results.xml
