name: Validate JS

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/validate-js.yml'
      - 'src/**'
      - '__tests__/**'
      - '*.json'
      - '*.js'
      - '*.lock'
      - 'examples/bare/src/**'
      - 'examples/bare/*.json'
      - 'examples/bare/*.js'
      - 'examples/bare/*.tsx'
      - 'examples/expo/app/**'
      - 'examples/expo/*.json'
      - 'examples/expo/*.js'
      - 'examples/expo/*.tsx'
  pull_request:
    paths:
      - '.github/workflows/validate-js.yml'
      - 'src/**'
      - '__tests__/**'
      - '*.json'
      - '*.js'
      - '*.lock'
      - 'examples/bare/src/**'
      - 'examples/bare/*.json'
      - 'examples/bare/*.js'
      - 'examples/bare/*.tsx'
      - 'examples/expo/app/**'
      - 'examples/expo/*.json'
      - 'examples/expo/*.js'
      - 'examples/expo/*.tsx'

jobs:
  validate:
    name: Validate JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn

      - name: Enable Corepack
        run: corepack enable

      - name: Install node_modules
        run: yarn install --immutable

      - name: Run PR test gate
        run: yarn test:pr
